# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{qcore}
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kris Leech"]
  s.date = %q{2010-04-01}
  s.description = %q{Qwerty Core}
  s.email = %q{kris.leech@interkonect.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "README",
     "Rakefile",
     "VERSION",
     "app/controllers/admin/users_controller.rb",
     "app/controllers/password_resets_controller.rb",
     "app/controllers/user_sessions_controller.rb",
     "app/controllers/users_controller.rb",
     "app/models/notifier.rb",
     "app/models/settings.rb",
     "app/models/user.rb",
     "app/models/user_session.rb",
     "app/views/admin/users/_form.erb",
     "app/views/admin/users/edit.html.erb",
     "app/views/admin/users/index.html.erb",
     "app/views/admin/users/new.html.erb",
     "app/views/admin/users/show.html.erb",
     "app/views/notifier/password_reset_instructions.erb",
     "app/views/notifier/registration_email.erb",
     "app/views/password_resets/edit.html.erb",
     "app/views/password_resets/new.html.erb",
     "app/views/user_sessions/new.html.erb",
     "app/views/users/_form.erb",
     "app/views/users/edit.html.erb",
     "app/views/users/new.html.erb",
     "app/views/users/show.html.erb",
     "config/example_routes.rb",
     "db/migrate/20090713104345_create_users.rb",
     "db/migrate/20091001201102_create_assignments.rb",
     "init.rb",
     "install.rb",
     "lib/qcore.rb",
     "lib/qcore/authentication.rb",
     "lib/qcore/authorization.rb",
     "qcore.gemspec",
     "rails/init.rb",
     "tasks/core_tasks.rake",
     "test/core_test.rb",
     "test/test_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://interkonect.com}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Qwerty Core}
  s.test_files = [
    "test/core_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
